config/routes.rb
Rails.application.routes.draw do
  namespace :frontend do
    resources :screens, only: [ :show ]
    get "/screens/:screen_id/fields/:field_id/content/", to: "content#index", as: "content"

    # The main landing page for the frontend player.
    get "/:id", to: "player#show", as: "player"
  end
  resources :screens do
    resources :subscriptions, only: [ :index, :create, :destroy ]
  end
  resources :templates
  resources :submissions
  resources :rss_feeds do
    get "refresh", on: :member
  end
  resources :feeds
  resources :rich_texts
  resources :graphics
  resources :contents, only: [ :index, :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/content.rb
class Content < ApplicationRecord
    has_many :submissions, dependent: :destroy
    has_many :feeds, through: :submissions

    def as_json(options = {})
        options[:methods] ||= [ :type ]
        options[:only] ||= [ :id, :duration ]
        super(options)
    end

    # should_render_in? determines if a piece of content is
    # suitable to be rendered in a given position.
    #
    # By default, it returns true.
    def should_render_in?(position)
      true
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # Common parameters for creating a content
  PARAMS = [ :name, :duration, :start_time, :end_time, feed_ids: [] ].freeze

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/new
  def new
    @content = Content.new
  end
end

app/controllers/frontend/content_controller.rb
class Frontend::ContentController < Frontend::ApplicationController
  def index
    @screen = Screen.find(params[:screen_id])
    @field = Field.find(params[:field_id])
    @position = Position.find(params[:position_id])

    @subscriptions = @screen.subscriptions.where(field_id: @field.id).to_a
    @content = @subscriptions.flat_map do |subscription|
      subscription.contents
    end

    # Remove content which should not be rendered in this position.
    # For example, a 4:3 graphic should probably not be rendered in a
    # long horizontal ticker field.
    @content.delete_if do |c|
      !c.should_render_in?(@position)
    end

    logger.debug "Found #{@content.count} content to render in #{@screen.name}'s #{@field.name} field"

    render json: @content
  end
end

app/controllers/frontend/contents_controller.rb
class Frontend::ContentsController < ApplicationController
  define_callbacks :index  # controller callback
  ConcertoPlugin.install_callbacks(self) # Get the callbacks from plugins

  layout false

  before_action :scope_setup
  before_action :screen_api

  DEFAULT_SHUFFLE = 'WeightedShuffle'

  def scope_setup
    @screen = Screen.find(params[:screen_id])
    @field = Field.find(params[:field_id])
    @subscriptions = @screen.subscriptions.where(field_id: @field.id)
    allow_screen_if_unsecured @screen
  end

  def index
    allow_cors unless !ConcertoConfig[:public_concerto]
    require 'frontend_content_order'

    shuffle_config = FieldConfig.get(@screen, @field, 'shuffler') || DEFAULT_SHUFFLE
    shuffler_klass = FrontendContentOrder.load_shuffler(shuffle_config)
    shuffler = nil

    run_callbacks :index do # Run plugin hooks
      # Get the screen time and consider it the same time in the server time zone.
      # For instance 5pm at the eastern campus would be 5pm in mountain time
      # if our server is in mountain time zone.  This is because we consider the content
      # display range as "time without zone".  If a user wants an item to show from 8 to 5
      # then it should show from 8 to 5 on all screens regardless of time zone it
      # is in -- it should be considered "local time".
      actual_screen_time = DateTime.parse(Clock.time.in_time_zone(@screen.time_zone).iso8601)
      screen_time = Time.zone.local(
        actual_screen_time.year,
        actual_screen_time.month,
        actual_screen_time.day,
        actual_screen_time.hour,
        actual_screen_time.minute,
        actual_screen_time.second
      )

      shuffler = shuffler_klass.new(@screen, @field, @subscriptions)

      # get the contents from the shuffler and reject what this screen would consider expired
      @content = shuffler.remove_consecutive(shuffler.next_contents()).reject{ |c| c.start_time > screen_time || c.end_time < screen_time }
    end

    auth! object: @content

    begin
      @content.each do |c|
        c.pre_render(@screen, @field)
      end
    rescue Exception => e
      logger.warn e.message
    end

    # Rails.logger.debug("--frontend contentscontroller index is sending setup-key of #{@screen.frontend_cache_key}")
    response.headers["X-Concerto-Frontend-Setup-Key"] = @screen.frontend_cache_key
    response.headers["ETag"] = Digest::MD5.hexdigest(@screen.frontend_cache_key +
      @content.collect { |e| e.id.to_s + e.data.to_s }.to_s)
    respond_to do |format|
      format.json {
        render json: @content.to_json(
          only: [:name, :id, :duration, :type],
          methods: [:render_details]
        )
      }
    end
    @screen.sometimes_mark_updated
  end

  # GET /frontend/1/fields/1/contents/1
  # Trigger the render function a piece of content and passes all the params
  # along for processing.  Should send an inline result of the processing.
  def show
    allow_cors unless !ConcertoConfig[:public_concerto]
    
    #response.headers["Cache-Control"] = 'no-cache' # no-cache means revalidate at server before pulling from cache
    @content = Content.find(params[:id])
    if @content.nil?
      logger.info "Skipping Deleted Content with id " + params[:id]
    else
      auth! object:@content
      rendered = @content.render(params)
      if rendered.is_a?(Media)
        @file = rendered
        send_data @file.file_contents, filename: @file.file_name, type: @file.file_type, disposition: 'inline'
        #fresh_when last_modified: @file.updated_at.utc, etag: @file
      elsif rendered.is_a?(Hash)
        render rendered
      end
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
    # Returns a +string+ of the path to render the partial for use in the grid view.
    #
    #   to_partial_path(graphic) # => "graphics/grid"
    def to_grid_partial_path(content)
        "#{ActiveSupport::Inflector.tableize(content.class.name)}/grid"
    end
end

app/helpers/frontend/contents_helper.rb
module Frontend::ContentsHelper
end

app/views/contents/_dynamic_content_tools.html.erb
<div class="subblock">
  <h3><%= t('.owner_tools') %></h3>
  <div>
    <%= link_to t('.force_update'), act_content_path(action_name: 'manual_refresh'), method: :put, class: "btn info" %>
    <%= link_to t('.purge_children'), act_content_path(action_name: 'delete_children'), method: :put, class: "btn info" %>
  </div>
</div>

app/views/contents/_edit_form.html.erb
<%= form_for(@content, html: { multipart: true }) do |f| %>
  <% type_folder = "contents/#{@content.type.underscore}" %>
  <%= hidden_field_tag :type, @content.type %>
  <% if lookup_context.exists?("#{type_folder}/edit_form", [], true) %>
    <%= render partial: "#{type_folder}/edit_form", locals: {form: f, content: @content} %>
  <% else %>
    <%= render :partial => "layouts/errors", :object => @content %>
    <div class="row-fluid">
      <div class="span8">
        <% if can?(:update_full_details, @content) && ['Ticker', 'HtmlText'].include?(@content.type) # only Ticker|HtmlText for now %>
          <%= render_partial_if("#{type_folder}/form_top", "form_top", {form: f}) %>
        <% end %>
        <%= render "form_middle", {:form => f} %>
        <%= ConcertoPlugin.render_view_hook self, :content_form, {form: f} %>
        <%= render "form_submit_feeds", {form: f} %>
      </div>
      <div class="span4">
        <fieldset>
          <legend><span><%=t('.preview')%></span></legend>
          <div id="preview_div">
            <%= render_content(@content) %>
          </div>
        </fieldset>
      </div>
    </div>

    <%= render  "form_bottom", {form: f, type: @content.type} %>
  <% end %>
<% end %>

app/views/contents/_form_bottom.html.erb
<div class="submit_bar actions">
  <%= form.submit t('.submit_content'), id: "submitContent-#{type}", class: "btn btn-primary" %> <%= link_to t(:cancel), browse_path, class: "btn" %>
</div>

app/views/contents/_form_middle.html.erb
<fieldset>
  <legend><span><%=t('contents.provide_details')%></span></legend>
  <div class="row-fluid">
    <div class="span6">
      <div class="clearfix">
        <%= form.label :name %>
        <%= form.text_field :name, style: "width: 85%;" %>
      </div>

      <%= render partial: 'contents/form_elements/dates', locals: {form: form} %>
    </div>
    <div class="span6">
      <%= render partial: 'contents/form_elements/duration', locals: {form: form, min: ConcertoConfig[:min_content_duration].to_i, max: ConcertoConfig[:max_content_duration].to_i} %>
    </div>
  </div>
</fieldset>

app/views/contents/_form_submit_feeds.html.erb
<fieldset>
  <legend><span><%=t('contents.submit_to_feeds')%></span></legend>
  <div class="clearfix">
    <%= render partial: 'contents/form_elements/feeds' %>
  </div>
</fieldset>

app/views/contents/_form_top.html.erb
<fieldset>
  <legend><span><%=t('.data')%></span></legend>
  <div class="clearfix">
    <label><%=t('.data')%></label>
    <div class="input">
      <%= form.text_field :data, class: "input-xlarge" %>
    </div>
  </div>
</fieldset>

app/views/contents/_grid.html.erb
<div id="contents" class="flex flex-wrap gap-4 my-4">
  <% contents.each do |content| %>
    <%= link_to content, class: "block" do %>
    <div class="block w-64 h-full pb-4 border-2 text-center bg-white">
      <%= render partial: to_grid_partial_path(content), locals: {content: content} %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/contents/_render_default.html.erb
<div class="default-padding">
  <%= content.data %>
</div>

app/views/contents/_render_grid.html.erb
<%= image_tag("ph/grid_ph.jpg", class: "with-shadow") %>

app/views/contents/_render_tile.html.erb
<div class="default-padding">
  <%= content.data %>
</div>

app/views/contents/_table.html.erb
<% if !@contents.empty? %>
  <table cellpadding="0" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th><%= t('.link') %></th>
        <th><%= t('.title') %></th>
        <th><%= t('.description') %></th>
        <th><%= t('.submitted') %></th>
        <th><%= t('.updated') %></th>
      </tr>
    </thead>
    <tbody>
      <% @contents.each do |content| %>
        <tr>
          <td>
            <%= link_to content do %>
              <%= image_tag("icons/icon_#{content.type}_40.png", {alt: "View Content", width: "40px", height: "40px"}) %>
            <% end %>
          </td>
          <td><%= link_to content do %><h2><%=h content.name %></h2><% end %></td>
          <td><p><%=h content.data %></p></td>
          <td><%=h l(content.created_at, format: :date) unless content.updated_at.nil? %></td>
          <td><%=h l(content.updated_at, format: :date) unless content.updated_at.nil? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<div style="clear:both;"></div>

app/views/contents/add_feed.js.erb
$("#event-selectedFeedList").append("<%= escape_javascript(render partial: 'contents/form_elements/selected_feed_display', locals: { feed: @feed, feed_index: @feed_index }) %>");
$("#event-zeroFeedsMsg").hide();
$('#select-feeds-btn').qtip('api').hide();

app/views/contents/edit.html.erb
<section class="viewblock">
  <header class="viewblock-header">
    <div class="viewblock-header_right default-padding">  &nbsp;
    </div>
    <h1 class="default-padding"><%= t('.edit_content', type: @content.class.display_name)%></h1>
  </header>
  <div class="viewblock-cont">
    <%= render 'edit_form' %>
  </div>
</section>

app/views/contents/new.html.erb
<%= page_title "Add Content" %>

<div class="flex space-x-4">
  <%= link_to new_graphic_path, class: "btn" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 mr-2">
      <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
    <span>Add Graphic</span>
  <% end %>

  <%= link_to new_rich_text_path, class: "btn" do%>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 mr-2">
      <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
    </svg>
    <span>Add Text / HTML</span>
  <% end %>
</div>


<div class="mt-8">
  <%= link_to "Back to contents", contents_path %>
</div>