config/routes.rb
Rails.application.routes.draw do
  namespace :frontend do
    resources :screens, only: [ :show ]
    get "/screens/:screen_id/fields/:field_id/content/", to: "content#index", as: "content"

    # The main landing page for the frontend player.
    get "/:id", to: "player#show", as: "player"
  end
  resources :screens do
    resources :subscriptions, only: [ :index, :create, :destroy ]
  end
  resources :templates
  resources :submissions
  resources :rss_feeds do
    get "refresh", on: :member
  end
  resources :feeds
  resources :rich_texts
  resources :graphics
  resources :contents, only: [ :index, :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/rich_text.rb
class RichText < Content
    store_accessor :config, :render_as

    # render_as is an enum-like structure. Ideally we would use rails'
    # ActtiveRecord::Enum functionality, but it doesn't work store_accessor.
    def html? = render_as == "html"
    def plaintext? = render_as == "plaintext"

    def self.render_as
        { plaintext: "plaintext", html: "html" }
    end

    def as_json(options = {})
        super(options).merge({
            render_as: render_as,
            text: text
        })
    end
end

app/controllers/rich_texts_controller.rb
class RichTextsController < ApplicationController
  before_action :set_rich_text, only: %i[ show edit update destroy ]

  # GET /rich_texts or /rich_texts.json
  def index
    @rich_texts = RichText.all
  end

  # GET /rich_texts/1 or /rich_texts/1.json
  def show
  end

  # GET /rich_texts/new
  def new
    @rich_text = RichText.new
  end

  # GET /rich_texts/1/edit
  def edit
  end

  # POST /rich_texts or /rich_texts.json
  def create
    @rich_text = RichText.new(rich_text_params)

    respond_to do |format|
      if @rich_text.save
        format.html { redirect_to rich_text_url(@rich_text), notice: "Rich text was successfully created." }
        format.json { render :show, status: :created, location: @rich_text }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rich_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rich_texts/1 or /rich_texts/1.json
  def update
    respond_to do |format|
      if @rich_text.update(rich_text_params)
        format.html { redirect_to rich_text_url(@rich_text), notice: "Rich text was successfully updated." }
        format.json { render :show, status: :ok, location: @rich_text }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rich_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rich_texts/1 or /rich_texts/1.json
  def destroy
    @rich_text.destroy!

    respond_to do |format|
      format.html { redirect_to rich_texts_url, notice: "Rich text was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rich_text
      @rich_text = RichText.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rich_text_params
      params.require(:rich_text).permit(*ContentsController::PARAMS, :text, :render_as)
    end
end

app/helpers/rich_texts_helper.rb
module RichTextsHelper
end

app/views/rich_texts/_form.html.erb
<%= form_with(model: rich_text) do |form| %>
<div class="grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
  <% if rich_text.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rich_text.errors.count, "error") %> prohibited this rich_text from being saved:</h2>

      <ul>
        <% rich_text.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sm:col-span-2">
    <%= form.label :render_as, "Type", class: "frm-label" %>
    <%= form.select :render_as, RichText.render_as, class: "frm-input" %>
  </div>

  <div class="sm:col-span-full">
    <%= form.label :text, class: "frm-label" %>
    <%= form.text_area :text, class: "frm-input" %>
  </div>

  <%= render "contents/form", form: form %>

  <div>
    <%= form.submit class: "btn" %>
  </div>
</div>
<% end %>

app/views/rich_texts/_grid.html.erb
<h2 class="text-lg"><%= content.name %></h2>
<div class="mt-1 bg-gray-200"><%= content.text %></div>

app/views/rich_texts/_rich_text.html.erb
<div id="<%= dom_id rich_text %>">
  <p>
    <strong>Name:</strong>
    <%= rich_text.name %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= rich_text.duration %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= rich_text.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= rich_text.end_time %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= rich_text.text %>
  </p>

  <p>
    <strong>Render As:</strong>
    <%= rich_text.render_as %>
  </p>
</div>

app/views/rich_texts/edit.html.erb
<h1>Editing rich text</h1>

<%= render "form", rich_text: @rich_text %>

<br>

<div>
  <%= link_to "Show this rich text", @rich_text %> |
  <%= link_to "Back to rich texts", rich_texts_path %>
</div>

app/views/rich_texts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rich texts</h1>

<div id="rich_texts">
  <% @rich_texts.each do |rich_text| %>
    <%= render rich_text %>
    <p>
      <%= link_to "Show this rich text", rich_text %>
    </p>
  <% end %>
</div>

<%= link_to "New rich text", new_rich_text_path %>

app/views/rich_texts/new.html.erb
<%= page_title "Add Text / HTML" %>

<%= render "form", rich_text: @rich_text %>

<div class="mt-8">
  <%= link_to "Back to rich texts", rich_texts_path %>
</div>

app/views/rich_texts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rich_text %>

<div>
  <%= link_to "Edit this rich text", edit_rich_text_path(@rich_text) %> |
  <%= link_to "Back to rich texts", rich_texts_path %>

  <%= button_to "Destroy this rich text", @rich_text, method: :delete %>
</div>