config/routes.rb
Rails.application.routes.draw do
  namespace :frontend do
    resources :screens, only: [ :show ]
    get "/screens/:screen_id/fields/:field_id/content/", to: "content#index", as: "content"

    # The main landing page for the frontend player.
    get "/:id", to: "player#show", as: "player"
  end
  resources :screens do
    resources :subscriptions, only: [ :index, :create, :destroy ]
  end
  resources :templates
  resources :submissions
  resources :rss_feeds do
    get "refresh", on: :member
  end
  resources :feeds
  resources :rich_texts
  resources :graphics
  resources :contents, only: [ :index, :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :screen
  belongs_to :field
  belongs_to :feed

  def contents
    self.feed.content
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_screen
  before_action :set_subscription, only: %i[ destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = @screen.subscriptions
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.screen = @screen

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to screen_subscriptions_url(@screen), notice: "#{@subscription.field.name} field subscription to #{@subscription.feed.name} feed was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy!

    respond_to do |format|
      format.html { redirect_to screen_subscriptions_url(@screen), notice: "#{@subscription.field.name} field subscription to #{@subscription.feed.name} feed was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Subscription URLs are always nested under a screen.
    def set_screen
      @screen = Screen.find(params[:screen_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:field_id, :feed_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_add_subscription.html.erb
<div id="add-sub">
  <% feeds = dfs_tree(Feed.roots) %>
  <% feeds.reject!{ |feed| !allowed_feeds.include?(feed) && !current_feeds.include?(feed)} %>
    <% if feeds.empty? %>
      <p><%= t 'contents.form_elements.feeds.no_feeds' %></p>
    <% else %>

    <div class="tooltip-filter-cont">
      <input type="text" class="feed_filter fillWidth" placeholder="Type here to filter"/>
    </div>

    <div class="tooltip-scrollY">
      <ul class="filterable selector-list">
      <% feeds.each_with_index do |feed, i| %>
        <li data-filter="<%= feed.name %>" class="<%= "checked" if current_feeds.include?(feed) %>">
          <% if current_feeds.include?(feed) %>
            <%= ("&nbsp;" * feed.depth).html_safe %>
            <i class="fas fa-thumbs-up"></i>
            <b><%= feed.name %></b>
            <b><%= feed.name %></b>
          <% else %>
            <%= link_to screen_field_subscriptions_path(@screen, @field, subscription: {feed_id: feed.id, weight: 1}), {method: :post, remote: true}, class: "link-hl", "data-feed-id" => feed.id do %>
              <%= ("&nbsp;" * feed.depth).html_safe %>
              <i class="fas fa-thumbs-up"></i>
              <b><%= feed.name %></b>
            <% end %>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/subscriptions/_form.html.erb
<%= form_with(model: [subscription.screen, subscription]) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :field_id, value: subscription.field_id %>

  <div class="my-2">
    <%= form.label :feed_id, class: "frm-label" %>
    <%= form.collection_select :feed_id, Feed.all, :id, :name %>
  </div>

  <div>
    <%= form.submit class: "btn" %>
  </div>
<% end %>

app/views/subscriptions/_new_subscription_tr.html.erb
<tr>
  <td>
    <h2><%= feed.name %></h2>
    <h4 class="color-gray"><%= t('subscriptions.approved_content', count: feed.approved_contents.size)  %></h4>
    <%= hidden_field_tag "subscription_id[#{i}]", "" %>
    <%= hidden_field_tag "subscription_feed[#{i}]", feed.id, class: "marker-sub-feed" %>
  </td>
  <td>
    <div class="clearfix frequency" id="sub-freq-<%= i %>">
      <div class="leftseconds" style="width: 50px;"><%= t('subscriptions.shown_rarely') %></div>
      <%= range_field :subscription_weight, i, { min: 1, max: Subscription::WEIGHTS.size, step: 1, class: "frequency_range thin" } %>
      <div class="rightseconds" style="width: 50px;"><%= t('subscriptions.shown_frequently') %></div>
    </div>
  </td>
  <td>
    <%= link_to "#", {data: { confirm: t(:are_you_sure_remove_model_key, model: Feed.model_name.human, key: feed.name) }, class: "btn btn-danger btnRemoveSubscription"} do %>
      <i class="fas fa-minus-circle"></i> <%= t(:remove_model, model: Feed.model_name.human) %>
    <% end %>
  </td>
</tr>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>"class="p-4 border-2 bg-white my-4">
  <div class="text-lg font-medium"><%= subscription.feed.name %></div>
  <%= button_to "Unsubscribe", [@screen, subscription], method: :delete, class: "btn" %>
</div>

app/views/subscriptions/_subscription_tr.html.erb
<tr>
  <td style="width: 50px;">
    <% if can? :destroy, subscription %>
      <%= link_to screen_field_subscription_path(@screen, @field, subscription), method: :delete, remote: true, class: "btn btn-danger btnRemoveSubscription" do %>
        <i class="fas fa-minus-circle"></i>
      <% end %>
    <% end %>
  </td>
  <td>
    <h2><%= subscription.feed.name %></h2>
    <h4 class="color-gray"><%= t('subscriptions.approved_content', count: subscription.feed.approved_contents.active.where(kind_id: @field.kind_id).count) %></h4>
  </td>
  <td>
    <div class="clearfix frequency">
      <div class="leftseconds" style="width: 50px;"><%= t('subscriptions.shown_rarely') %></div>
      <% can_edit = can? :edit, subscription %>
      <%= range_field_tag 'subscription[weight]', subscription.weight, { min: 1, max: Subscription::WEIGHTS.size, step: 1, class: "frequency_range thin",
           data: (can_edit ? {remote: true, url: screen_field_subscription_path(@screen, @field, subscription), method: :put} : {}), disabled: !can_edit } %>
      <div class="rightseconds" style="width: 50px;"><%= t('subscriptions.shown_frequently') %></div>
    </div>
  </td>
</tr>

app/views/subscriptions/create.js.erb
$("#subscriptions-list").append("<%= escape_javascript(render partial: 'subscription_tr', locals: { subscription: @subscription }) %>");
initializeFrequencySliders();
$('#add-sub-btn').qtip('api').hide();

app/views/subscriptions/index.html.erb
<%= page_title "#{@screen.name} Subscriptions" %>
<% content_for :subheader do %>
  <div><%= link_to "Back to screen", @screen, class: "underline" %></div>
<% end %>
<p style="color: green"><%= notice %></p>

<% active_subscriptions = [] %>
<% @screen.template.positions.each do |position| %>
  <div id="<%= dom_id position %>" class="my-2">
    <h2 class="text-xl font-semibold"><%= position.field.name %> Field</h2>
    <% @screen.subscriptions.where(field: position.field).each do |subscription| %>
      <% active_subscriptions.push(subscription) %>
      <%= render subscription %>
    <% end %>
    <div class="p-4 border-2 bg-white my-4">
      <h3 class="font-semibold">Add Subscription</h3>
      <%= render "form", subscription: Subscription.new(screen: @screen, field: position.field) %>
    </div>
  </div>
<% end %>

<% inactive_subscriptions = @subscriptions - active_subscriptions %>
<% if !inactive_subscriptions.empty? %>
<div>
  <h2 class="text-xl font-semibold">Inactive Subscriptions<h2>
  <div class="italic text-sm p-2">Subscriptions not used in the current template.</div>
  <% inactive_subscriptions.group_by{|s| s.field_id }.each do |field_id, subscriptions| %>
    <h3 class="font-semibold"><%= subscriptions.first.field.name %> Field</h3>
    <% subscriptions.each do |subscription| %>
      <%= render subscription %>
    <% end %>
  <% end %>
  </div>
</div>
<% end %>

app/views/subscriptions/new.js.erb
$('#add-sub-btn').qtip('api').set('content.text', '<%= escape_javascript(render partial: 'subscriptions/add_subscription', locals: {allowed_feeds: Feed.subscribable(@screen, @field), current_feeds: @subscriptions.collect {|s| s.feed}}) %>');
initFeedFilters();