config/routes.rb
Rails.application.routes.draw do
  namespace :frontend do
    resources :screens, only: [ :show ]
    get "/screens/:screen_id/fields/:field_id/content/", to: "content#index", as: "content"

    # The main landing page for the frontend player.
    get "/:id", to: "player#show", as: "player"
  end
  resources :screens do
    resources :subscriptions, only: [ :index, :create, :destroy ]
  end
  resources :templates
  resources :submissions
  resources :rss_feeds do
    get "refresh", on: :member
  end
  resources :feeds
  resources :rich_texts
  resources :graphics
  resources :contents, only: [ :index, :new ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/field.rb
class Field < ApplicationRecord
    has_many :positions

    serialize :alt_names, coder: JSON, type: Array

    has_many :subscriptions
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:edit, :update, :destroy]

  # GET /fields
  def index
    authorize! :read, Field
    @fields = Field.all
  end

  # GET /fields/new
  def new
    @field = Field.new
    auth!
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  def create
    @field = Field.new(field_params)
    auth!
    if @field.save
      redirect_to fields_path, notice: t(:was_created, name: @field.name, theobj: t(:field))
    else
      render :new
    end
  end

  # PATCH/PUT /fields/1
  def update
    if @field.update(field_params)
      redirect_to fields_path, notice: t(:was_updated, name: @field.name, theobj: t(:field))
    else
      render :edit
    end
  end

  # DELETE /fields/1
  def destroy
    @field.destroy
    redirect_to fields_url, notice: t(:was_deleted, name: @field.name, theobj: t(:field))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
      auth!
    end

    # Only allow a trusted parameter "white list" through.
    def field_params
      params.require(:field).permit(:name, :kind_id)
    end
end

app/controllers/frontend/fields_controller.rb
class Frontend::FieldsController < ApplicationController
  layout false
end

app/helpers/fields_helper.rb
module FieldsHelper
  def field_templates(field)
    templates = Array.new
    field.positions.each do |p| 
      templates << p.template unless templates.include?(p.template)
    end
    templates.sort{|a, b| a.name <=> b.name}
  end
end

app/helpers/frontend/fields_helper.rb
module Frontend::FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <%= render partial: "layouts/errors", object: @field %>
  <fieldset>
  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name, class: "input-small" %>
    </div>
  </div>  
  <div class="clearfix">
    <%= f.label :kind %>
    <div class="input">
      <%= f.select :kind_id, options_for_select(Kind.all.map{|k|[k.name, k.id]}, @field.kind_id) %>
    </div>
  </div>    
  </fieldset>
  <div class="submit_bar actions">
    <% if @field.new_record? %>
      <%= f.submit t(:create_model, model: Field.model_name.human), class: "btn btn-primary" %>
    <% else %>
      <%= f.submit t(:update_model, model: Field.model_name.human), class: "btn btn-primary" %>
    <% end %>
    <%= link_to t(:cancel), fields_path, class: "btn" %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<section class="viewblock">
  <header class="viewblock-header">
   <div class="viewblock-header_right">
      <div class="button-padding">
        <% if can? :delete, @field %>
          <%= link_to t(:destroy_model, model: Field.model_name.human), @field, data: { confirm: t(:are_you_sure_delete_model_key, model: Field.model_name.human, key: sanitize(@field.name)) }, method: :delete, class: "btn" %>
        <% end %>
      </div>
    </div>

    <h1 class="default-padding">
      <%= link_to t(:manage_model, model: Field.model_name.human(count: 42)), fields_path %> > <%= @field.name.titleize %>
    </h1>
  </header>
  <div class="viewblock-cont">
     <%= render 'form' %>
  </div>
</section>

app/views/fields/index.html.erb
<section class="viewblock fields-index">
  <header class="viewblock-header">
    <div class="viewblock-header_right">
      <div class="button-padding">
        <% if can? :create, Field %>
          <%= link_to t(:new_model, model: Field.model_name.human), new_field_path, class: "btn" %>
        <% end %>
      </div>
    </div>
    <h1 class="default-padding">
      <%= t :manage_model, model: Field.model_name.human.pluralize %>
    </h1>
  </header>
  <div class="viewblock-cont">
    <div class="default-padding">
    <table>
      <thead>
        <tr>
          <th><%= ConcertoPlugin.human_attribute_name(:field_name) %></th>
          <th><%= t('.field_kind')%></th>
          <th><%= t('.used_in_templates')%></th>
        </tr>
      </thead>
      <tbody>
        <% @fields.each do |field| %>
          <tr>
            <td><%= link_to(field.name.titleize, action: :edit, id: field.id) %></td>
            <td><%= field.kind.name %></td>
            <td>
              <ul class="members-list">
                <%= render field_templates(field) %>
              </ul>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</section>

app/views/fields/new.html.erb
<section class="viewblock">
  <header class="viewblock-header">
    <h1 class="default-padding">
      <%= link_to t(:manage_model, model: Field.model_name.human(count: 42)), fields_path %> > New
    </h1>
  </header>
  <div class="viewblock-cont">
     <%= render 'form' %>
  </div>
</section>